application: developer-support-handbook
version: 2
runtime: python
api_version: 1

handlers:
- url: /
  static_files: _build/html/index.html
  upload: _build/html/index.html

- url: /
  static_dir: _build/html/
